# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255, verbose_name='Name')),
                ('album_cover', models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Album Cover (240px x 240px)')),
                ('album_location', models.CharField(max_length=150, verbose_name='Location')),
                ('album_description', models.CharField(max_length=350, verbose_name='Description')),
                ('album_photographer', models.CharField(max_length=350, verbose_name='Photographer (Instagram Handle)')),
                ('album_model', models.CharField(max_length=350, verbose_name='Model (Instagram Handle)')),
                ('shoot_date', models.DateField(verbose_name='Shoot Date')),
                ('album_type', models.CharField(choices=[('collaboration', 'Collaboration'), ('modeling', 'Modeling'), ('photography', 'Photography'), ('senior photos', 'Senior Photos')], max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
