# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-13 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_caption', models.CharField(max_length=255, verbose_name='Caption')),
                ('product_photo', models.ImageField(upload_to='media/', verbose_name='Picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Apparel_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Name')),
                ('product_gender_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=256)),
                ('product_brand', models.CharField(max_length=25, verbose_name='Brand')),
                ('product_sizes', models.CharField(max_length=25, verbose_name='Sizes')),
                ('product_colors', models.CharField(max_length=25, verbose_name='Colors')),
                ('product_price', models.CharField(max_length=10, verbose_name='Price')),
                ('product_description', models.CharField(max_length=500, verbose_name='Description')),
                ('product_shipping_options', models.CharField(max_length=250, verbose_name='Shipping Options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apparel Product',
                'verbose_name_plural': 'Apparel Products',
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='apparel_picture',
            name='master_apparel_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apparel_Product', verbose_name='Apparel Product'),
        ),
    ]
