# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180212_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.CharField(max_length=255, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_apparel_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apparel_Product', verbose_name='Apparel Product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
