# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-14 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_apparel_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel_shipping',
            name='shipping_method',
            field=models.CharField(default='12', max_length=255, verbose_name='Shipping Method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apparel_shipping',
            name='shipping_price',
            field=models.CharField(max_length=255, verbose_name='Shipping Price'),
        ),
    ]
