# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180213_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel_Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Apparel_Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, verbose_name='Size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.RemoveField(
            model_name='apparel_product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='apparel_product',
            name='product_shipping_options',
        ),
        migrations.AlterField(
            model_name='apparel_product',
            name='product_gender_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=256, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='apparel_sizes',
            name='master_apparel_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apparel_Product', verbose_name='Apparel Product'),
        ),
        migrations.AddField(
            model_name='apparel_colors',
            name='master_apparel_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apparel_Product', verbose_name='Apparel Product'),
        ),
    ]
