# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-14 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180214_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel_product',
            name='product_colors',
        ),
        migrations.RemoveField(
            model_name='apparel_product',
            name='product_sizes',
        ),
    ]
