# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-15 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180214_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel_product',
            name='product_cover',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/', verbose_name='Album Cover (240px x 240px)'),
        ),
    ]
