# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_apparel_product_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel_product',
            name='real_brand_price',
            field=models.CharField(default='$85.99', max_length=500, verbose_name='Real Brand Price'),
            preserve_default=False,
        ),
    ]
