# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_apparel_product_real_brand_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel_price',
            name='master_apparel_product',
        ),
        migrations.AddField(
            model_name='apparel_product',
            name='product_price',
            field=models.CharField(default='$38.99', max_length=500, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Apparel_Price',
        ),
    ]
