# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_apparel_product_paypal_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=25)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_subject', models.CharField(max_length=75)),
                ('contact_message', models.CharField(max_length=750)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Response',
                'verbose_name_plural': 'Contact Responses',
            },
        ),
    ]
