# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel_product',
            name='product_description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
    ]
