# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180218_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apparel_Product',
            new_name='Apparel',
        ),
        migrations.RenameModel(
            old_name='Apparel_Colors',
            new_name='Colors',
        ),
        migrations.RenameModel(
            old_name='Apparel_Picture',
            new_name='Picture',
        ),
        migrations.RenameModel(
            old_name='Apparel_Shipping',
            new_name='Shipping',
        ),
        migrations.RenameModel(
            old_name='Apparel_Sizes',
            new_name='Sizes',
        ),
    ]
