# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180218_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Female'), ('kids', 'Kids')], default='men', max_length=256, verbose_name='Product Type'),
            preserve_default=False,
        ),
    ]
