# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_apparel_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_email', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Email',
                'verbose_name_plural': 'Newsletter Emails',
            },
        ),
        migrations.AlterField(
            model_name='apparel',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=256, verbose_name='Product Type'),
        ),
    ]
