# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180330_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparel',
            name='paypal_button',
        ),
        migrations.AddField(
            model_name='apparel',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
