# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180406_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='onsale',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
